[INT-7625] Adding all possible repoNames to target property.
JupiterOne/graph-snyk pull request #121
Opened 2023-05-09 17:29 UTC by JuanManuelIbarlucea

Adding multiple possible ways to relate `CodeRepo` to `snyk_finding`, this way we won't break any exising relationship while fixing `gitlab_project` ones.

2023-05-09 18:20 UTC, mishelashala requested changes

2023-05-09 18:20 UTC, mishelashala commented on src/steps/findings/converters.ts
> +  const last = repoFullName?.split('/').pop();
Can we add a function for this?

```ts
const getRepoName = (name: string = ''): string => name.split('/').pop();

const last = getRepoName(repoFullName);
```

Also, if we can add a unit test would be awesome

2023-05-09 18:21 UTC, ndowmon commented on src/steps/findings/converters.ts
> +  const last = repoFullName?.split('/').pop();
why don't you add this as an additional response from `parseSnykProjectName()`

2023-05-11 19:56 UTC, JuanManuelIbarlucea commented on src/steps/findings/converters.ts
> +  const last = repoFullName?.split('/').pop();
Extracted function to the `parseSnykProjectName()` function + updated the unit test to reflect the change.

2023-05-11 20:04 UTC, mishelashala submitted a review, later dismissed

2023-05-11 20:05 UTC, ndowmon submitted a review, later dismissed

2023-05-11 20:20 UTC, mishelashala approved these changes

2023-05-11 20:35 UTC, merged